TicketList/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from ticket import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', views.login_page, name='login'),
    url(r'^main$', views.inicio, name='inicio'),
    url(r'^logout$', views.logout_page, name="logout"),
    # Navegacion para Roles.
    url(r'^rol/add', views.RoleAgregar),
    url(r'^rol/new', views.RoleNuevo, name="RolesNuevo"),
    url(r'^rol/todos', views.RolesList, name="RolesList"),
    url(r'^rol/editar/(?P<id>\d+)', views.RolesEditar, name="RolesEditar"),
    url(r'^rol/update/(?P<id>\d+)', views.RolesUpdate),
    url(r'^rol/detalle/(?P<id>\d+)', views.RolesDetalles, name="RolesEditar"),
    url(r'^rol/asignarPermisos/(?P<id>\d+)', views.RolesAsignarPermisos, name="RolesAsignar"),
    url(r'^rol/sacarPermiso/(?P<idGrupo>\d+)/(?P<idPermiso>\d+)', views.RolesSacarPermisos),
    # Navegacion de usuarios.
    url(r'^usuario/registrar', views.UserRegistrar, name="UsuarioRegistrar"),
    url(r'^usuario/listar', views.UserListar, name="UsuarioListar"),
    url(r'^usuario/detallar/(?P<id>\d+)', views.UserDetallar, name="UsuarioDetallar"),
    url(r'^usuario/actualizar/(?P<id>\d+)', views.UserActualizar, name="UsuarioDetallar"),
    url(r'^usuario/perfil', views.UserPerfil, name="UsuarioPerfil"),
    url(r'^usuario/CambiarPassword/(?P<id>\d+)', views.UserCambiarPassword, name="UsuarioCambiarPassword"),
    url(r'^usuario/primer-login', views.primerLogin, name="PrimerLogin"),
    url(r'^mi-cuenta', views.UserPerfil, name="MiCuenta"),


    url(r'^centrales/todos', views.centralesList, name="centralesList"),
    # Navegacion de Tickets.
    url(r'^ticket/registrar', views.ticketAgregar, name="TicketRegistrar"),
    url(r'^ticket/guardar', views.ticketGuardar, name="TicketGuardar"),
    url(r'^ticket/detalle/(?P<id>\d+)', views.TicketDetallar, name="TicketDetalle"),
    url(r'^ticket/editar/(?P<id>\d+)', views.ticketEditar, name="TicketEditar"),
    url(r'^ticket/actualizar/(?P<id>\d+)', views.ticketActualizar, name="TicketActualizar"),
    url(r'^ticket/eliminar/(?P<id>\d+)', views.ticketEliminar, name="TicketEliminar"),

    url(r'^ticket/mis-tickets', views.ticketMisTickets, name="misTickets"),
    url(r'^ticket/pendientes', views.ticketPendientesList, name="TicketPendientes"),
    url(r'^ticket/atendidos', views.ticketAntendidosList, name="TicketAtendidos"),
    url(r'^ticket/solucionados', views.ticketSolucionadosList, name="TicketSolucionados"),
    url(r'^ticket/no-solucionados', views.ticketNoSolucionadosList, name="TicketNoSolucionados"),
    url(r'^ticket/atender/(?P<id>\d+)', views.ticketAtender, name="atenderTicket"),
    url(r'^ticket/solucionar/(?P<id>\d+)', views.ticketSolucionado, name="solucionarTicket"),

    url(r'^ticket/comentario/agregar/(?P<id>\d+)', views.ticketGuardarComentario, name="TicketGuardarComentario"),

    url(r'^ticket/sin-solucion/(?P<id>\d+)', views.ticketNoSolucionadoEdit, name="sinSolucionTicket"),
    url(r'^ticket/no-solucionar/(?P<id>\d+)', views.ticketNoSolucionar, name="noSolucionarTicket"),

    url(r'^ticket/actualizaciones-ajax/', views.ticketPushActualizaciones, name="TicketPush"),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ticket/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Central(models.Model):
    descripcion = models.CharField(max_length=64)

class Inconveniente(models.Model):
    descripcion = models.CharField(max_length=20)

class Motivo(models.Model):
    descripcion = models.CharField(max_length=64)

class Ticket(models.Model):
    """
        Se encarga de manejar las plantillas (tipos) para los user stories.

        :param descripcionBreve: Char Field
        :param comentario: Text Field
    """
    descripcionBreve = models.TextField()
    shelter = models.CharField(max_length=128)
    inconveniente = models.ForeignKey(Inconveniente, null=False, on_delete=models.CASCADE)
    motivo = models.ForeignKey(Motivo, null=True, on_delete=models.CASCADE)
    central = models.ForeignKey(Central, null=False, on_delete=models.CASCADE)
    fechaCreacion = models.DateTimeField(auto_now_add=True)
    fechaAtencion = models.DateTimeField(null=True, db_column='fecha_atencion');
    fechaCierre = models.DateTimeField(null=True, db_column='fecha_cierre');
    usuarioCreacion = models.ForeignKey(User, related_name='usuario_creacion')
    usuarioEncargado = models.ForeignKey(User, related_name='usuario_encargado')
    estado = models.CharField(max_length=64)
    codigo = models.CharField(max_length=128, null=True)
    numeroAfectado = models.CharField(max_length=128, db_column='numero_afectado', null=True)
    fechaModificacion = models.DateTimeField(auto_now=True)

    class Meta:
        permissions = (
            ('change_state_ticket', 'Puede cambiar estado del ticket'),
            ('view_ticket', 'Puede listar los ticket'),
            ('view_pendientes_ticket', 'Puede listar los ticket pendientes'),
            ('view_atendidos_ticket', 'Puede listar los ticket atendidos'),
            ('view_solucionados_ticket', 'Puede listar los ticket solucionados'),
            ('view_no_solucionados_ticket', 'Puede listar los ticket no solucionados'),
        )

class Comentarios(models.Model):
    """
        Se encarga de manejar los comentarios de un user story.
        :param autor: Foreign Key Usuario
        :param titulo: Char Field
        :param comentario: Text Field
        :param fechaComentario: DateTime Field
        :param userStory: Foreign Key userStory
        :param lado: Integer Field
    """

    autor = models.ForeignKey(User)
    comentario = models.TextField()
    fechaComentario = models.DateTimeField(auto_now_add=True)
    ticket = models.ForeignKey(Ticket, null=True)
    lado = models.IntegerField()

class Persona(models.Model):
    usuario = models.ForeignKey(User)
    codigo = models.CharField(max_length=128)
    first_login = models.BooleanField(default=False)

templates/CentralList.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/main"><i class="fa fa-home" aria-hidden="true"></i></a></li>
            <li class="breadcrumb-item"><a href="/central/todos">Centrales</a></li>
            <li class="breadcrumb-item active">{{ titulo }}</li>
        </ol>

        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                      <th>#</th>
                      <th>Central</th>
                    </tr>
                </thead>
                <tbody>
                    {% for central in centralList %}
                    <tr>
                        <td>{{central.id}}</td>
                        <td>{{central.descripcion}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/RolesDetalles.html
{% extends 'base.html' %}
{% block content %}

    <div class="container-fluid">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/main"><i class="fa fa-home" aria-hidden="true"></i></a></li>
            {% if request.user.is_superuser %}
                <li class="breadcrumb-item"><a href="/rol/todos">Roles</a></li>
            {% endif %}
            <li class="breadcrumb-item active">Detalle Rol</li>
        </ol>
        <div class="col-lg-12">
            <h2 class="page-header">Rol: {{ rol.name }}</h2>
        </div>


        <!-- Lista de Permisos que se desean asignar -->
        <label>Seleccione los permisos que desea agregar: </label>
        <div class="panel-body">
            <div class="dataTable_wrapper">
                <form action="/rol/asignarPermisos/{{ rol.id }}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <select multiple class="form-control" name="PermisosList">
                            {% for obj in permisos %}
                                <option value="{{ obj.id }}">{{ obj.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div style="text-align: center">
                        <a href="/rol/todos" class="btn btn-primary">Atrás</a>
                        <input type=submit value="Asignar" class="btn btn-primary">
                    </div>

                </form>
            </div>
        </div>

        <label> Permisos Asignados </label>
        <div class="panel-body">
            <div class="dataTable_wrapper">
                <table class="table table-hover" id="PermisosActivos">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Permiso</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for perm in permGrupos %}
                        <tr>
                            <td>{{ perm.id }}</td>
                            <td>{{ perm.codename }}</td>
                            <td><a href='javascript:confirmar("/rol/sacarPermiso/{{ rol.id }}/{{ perm.id }}")'
                                   class="btn btn-sq-xs btn-primary">
                                <i class="fa fa-remove fa-1x"></i><br/></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/RolesEdit.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/main"><i class="fa fa-home" aria-hidden="true"></i></a></li>
            {% if request.user.is_superuser %}
                <li class="breadcrumb-item"><a href="/rol/todos">Roles</a></li>
            {% endif %}
            <li class="breadcrumb-item active">{{ titulo }}</li>
        </ol>

        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">{{ titulo }}</h2>
            </div>
            <!-- /.col-lg-12 -->
        </div>

        <div class="panel-body">
            <div class="col-lg-5">

                <form role="form" action="{{ action }}" method="post">{% csrf_token %}
                    <div class="form-group">
                        <label for="nombreRol">Nombre : </label>
                        <input class="form-control" id="nombreRol"
                               placeholder="Nombre para el Rol" name="groupName"
                               value="{{ rol.name }}" required>
                    </div>
                    <div style="text-align: center">
                        <a href="/rol/todos" class="btn btn-primary">Atrás</a>
                        <input type=submit value="Guardar" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/RolesList.html
{% extends 'base.html' %}
{% block content %}

    <div class="container-fluid">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/main"><i class="fa fa-home" aria-hidden="true"></i></a></li>
            {% if request.user.is_superuser %}
                <li class="breadcrumb-item active"><a href="/rol/todos">Roles</a></li>
            {% endif %}
        </ol>
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Roles</h2>
            </div>
            <!-- /.col-lg-12 -->
        </div>

        <div class="panel-body">

            <div class="dataTable_wrapper" style="width:70%" align="center">
                <table class="table table-bordered" id="listarRoles">
                    <thead>
                    <tr>
                        <th>Rol</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for rol in RolesList %}
                        <tr>
                            <td>{{ rol.name }}</td>
                            <td>
                                <a href="/rol/editar/{{ rol.id }}" class="btn btn-sq-xs btn-primary"><i
                                        class="fa fa-pencil fa-1x"></i><br/></a>
                                <a href="/rol/detalle/{{ rol.id }}" class="btn btn-sq-xs btn-primary"><i
                                        class="fa fa-info fa-1x"></i><br/></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div style="text-align: center">
                    <a href='/rol/new' class="btn btn-primary">Crear Rol</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/TicketDetalle.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">

        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/main"><i class="fa fa-home" aria-hidden="true"></i></a></li>
            <li class="breadcrumb-item"><a href="/ticket/todos">Tickets</a></li>
            <li class="breadcrumb-item active">Detalle</li>
        </ol>
    <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">{{ ticket.inconveniente.descripcion }}</h1>

          <!-- Author -->
          <p class="lead">
            Creado por
            <a href="#">{{ ticket.usuarioCreacion }}</a>
          </p>

          <hr>
            <!-- Post Content -->
          <p class="lead">
              {{ ticket.descripcionBreve }}
          </p>
            <br>
              <small>Shelter: {{ ticket.shelter }}&nbsp;&nbsp;&nbsp;&nbsp; Numero: {{ ticket.numeroAfectado }}
              &nbsp;&nbsp;&nbsp;&nbsp;</small>
            <br>

            Marcado como
            {% if ticket.estado == 'PENDIENTE' %}
                <span class="badge badge-secondary">{{ ticket.estado }}</span>
            {% endif %}
            {% if ticket.estado == 'ATENDIDO' %}
                <span class="badge badge-warning">{{ ticket.estado }}</span>
            {% endif %}
            {% if ticket.estado == 'SOLUCIONADO' %}
                <span class="badge badge-success">{{ ticket.estado }}</span>
            {% endif %}
            {% if ticket.estado == 'NO_SOLUCIONADO' %}
                <span class="badge badge-danger">NO SOLUCIONADO</span>
            {% endif %}
            por {{ ticket.usuarioEncargado }}

          <hr>
            {% if ticket.estado == 'PENDIENTE' %}
                <div style="text-align: center">
                    <a href='/ticket/editar/{{ ticket.id }}' class="btn btn-primary btn-sm">
                        <i class="fa fa-pencil" aria-hidden="true"></i> Editar
                    </a>
                    <a href='/ticket/eliminar/{{ ticket.id }}' class="btn btn-primary btn-sm"
                       onclick="return confirm('Estas Seguro de Eliminar registro?')">
                        <i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar
                    </a>
                </div>
                <hr>
            {% endif %}

        <div class="activity-feed">
          <div class="feed-item">
            <div class="date">{{ ticket.fechaCreacion | date:'d-m-Y H:i'}}</div>
            <div class="text">Creado por {{ ticket.usuarioCreacion }} </div>
          </div>
            {% if ticket.estado == 'ATENDIDO' or ticket.estado == 'SOLUCIONADO' or ticket.estado == 'NO_SOLUCIONADO' %}
          <div class="feed-item">
            <div class="date">{{ ticket.fechaAtencion | date:'d-m-Y H:i'}}</div>
            <div class="text">Atendido por {{ ticket.usuarioEncargado }}</div>
          </div>
            {% endif %}
            {% if ticket.estado == 'SOLUCIONADO' or ticket.estado == 'NO_SOLUCIONADO'%}
          <div class="feed-item">
            <div class="date">{{ ticket.fechaCierre | date:'d-m-Y H:i'}}</div>
            <div class="text">Cerrado por {{ ticket.usuarioEncargado }} </div>
          </div>
            {% endif %}
        </div>
        <hr>
          <!-- Comments Form -->
          <div class="card my-4" style="background-color: #f5f8fa">
            <div class="card-body">
              <form role="form" action="{{ actionComentar}}" method="post">{% csrf_token %}
                <div class="form-group">
                  <textarea class="form-control" rows="3" name="comentario"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Comentar</button>
              </form>
            </div>
          </div>

          {% for coment in comentarios %}<!-- Single Comment -->
          <div class="media mb-4">
            <div class="media-body">
                <small style="color: #828e95"><strong>
                            {{ coment.autor }}
                        </strong> &bull; {{ coment.fechaComentario | date:'d-m-Y H:i'}}</small>
                <br />
              {{ coment.comentario }}
            </div>
          </div>
        {% endfor %}

        </div>
</div>
</div>
{% endblock %}

templates/TicketEdit.html
{% extends 'base.html' %}
{% block content %}

    <div class="container-fluid">

        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/main"><i class="fa fa-home" aria-hidden="true"></i></a></li>
            <li class="breadcrumb-item"><a href="/ticket/todos">Tickets</a></li>
            <li class="breadcrumb-item active">Agregar</li>
        </ol>

        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">{{ titulo }}</h2>
            </div>
            <!-- /.col-lg-12 -->
        </div>

        <div class="panel-body">
            <div class="col-lg-5">

                <form role="form" action="{{ action }}" method="post">{% csrf_token %}
                    <div class="form-group" id="shelterField">
                        <label for="desCorta">Shelter/Zona </label>
                        <input class="form-control" id="shelter"
                               placeholder="Zona del inconveniente" name="shelter"
                               value="{{ ticket.shelter}}" required>
                    </div>
                    <div class="form-group" id="inconvenienteField">
                        <label for="tipoUserStory">Inconveniente </label>
                        <select class="form-control" type="text" id="inconveniente" name="inconveniente">
                            <option value="">--Seleccione--</option>
                            {% for inc in inconvenientes %}
                                <option value="{{ inc.id }}"
                                        {% if inc.id == ticket.inconveniente.id %} selected {% endif %}>
                                    {{ inc.descripcion }} </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group" id="descripcionField">
                        <label for="desCorta">Descripción Breve </label>
                        <input class="form-control" id="descripcion"
                               placeholder="Descripcion del inconveniente" name="descripcion"
                               value="{{ ticket.descripcionBreve }}" required>
                    </div>

                    <div class="form-group" id="numeroField">
                        <label for="desCorta">Numero afectado </label>
                        <input class="form-control" id="numero"
                               placeholder="Numero del afectado" name="numero"
                               value="{{ ticket.numeroAfectado }}">
                    </div>
                    <div style="text-align: center">
                        <input type=submit value="Guardar" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>TicketList - Administra tus inconvenientes</title>
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css'%}" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-activity.css'%}" rel="stylesheet">

    <link href="{% static 'css/sb-admin.css'%}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/tickets.png' %}"/>
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top" onload="funcionMensaje()">

<!-- Simply Toast -->
<script>
    function funcionMensaje() {

        $.simplyToast.defaultOptions = {
            appendTo: "body",
            customClass: false,
            type: "info",
            offset: {
                from: "top",
                amount: 20
            },
            align: "right",
            minWidth: 250,
            maxWidth: 450,
            delay: 4000,
            allowDismiss: false,
            spacing: 10
        };

        <!--Mensaje de Resultado-->
        {% if messages %}
            {% for message in messages %}

                var mensaje = "{{ message }}"

                {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}

                    $.simplyToast(mensaje, 'info');

                {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}

                    $.simplyToast(mensaje, 'success');

                {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}

                    $.simplyToast(mensaje, 'warning');

                {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

                    $.simplyToast(mensaje, 'danger');

                {% endif %}

            {% endfor %}

        {% endif %}
    }

</script>


<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="/main">TicketList</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">

            {% if user.is_superuser %}
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Administración">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
                    <i class="fa fa-fw fa-gear"></i>
                    <span class="nav-link-text">Administracion</span>
                </a>
                <ul class="sidenav-second-level collapse" id="collapseMulti">
                    <li>
                        <a href="/rol/todos">Roles</a>
                    </li>
                    <li>
                        <a href="/usuario/listar">Usuarios</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Centrales">
                <a class="nav-link" href="/centrales/todos">
                    <i class="fa fa-fw fa-dashboard"></i>
                    <span class="nav-link-text">Centrales</span>
                </a>
            </li>
            {% endif %}

            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tickets">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseTicket" data-parent="#exampleAccordion">
                    <i class="fa fa-fw fa-tasks"></i>
                    <span class="nav-link-text">Tickets</span>
                </a>
                <ul class="sidenav-second-level collapse" id="collapseTicket">
                    <li>
                        <a href="/ticket/mis-tickets">Mis tickets</a>
                    </li>
                    {% if perms.ticket.view_pendientes_ticket %}
                    <li>
                        <a href="/ticket/pendientes">Pendientes</a>
                    </li>
                    {% endif %}
                    {% if perms.ticket.view_atendidos_ticket %}
                    <li>
                        <a href="/ticket/atendidos">Atendidos</a>
                    </li>
                    {% endif %}
                    {% if perms.ticket.view_solucionados_ticket %}
                    <li>
                        <a href="/ticket/solucionados">Solucionados</a>
                    </li>
                    {% endif %}
                    {% if perms.ticket.view_no_solucionados_ticket %}
                    <li>
                        <a href="/ticket/no-solucionados">No Solucionados</a>
                    </li>
                    {% endif %}
                </ul>
            </li>
            {% if perms.ticket.add_ticket %}
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Nuevo Ticket">
                <a class="nav-link" href="/ticket/registrar">
                    <i class="fa fa-fw fa-wrench"></i>
                    <span class="nav-link-text">Nuevo Ticket</span>
                </a>
            </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav sidenav-toggler">
            <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-left"></i>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-fw fa-gear"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                    <h6 class="dropdown-header">Configuraciones</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/mi-cuenta">
                        Mi cuenta
                    </a>
                </div>
            </li>
            <li class="nav-item"><a href="/logout" class="nav-link"><i class="fa fa-sign-out fa-fw"></i>Salir</a>
        </ul>
    </div>
</nav>
<div class="content-wrapper">
    <div class="container-fluid">

        {% block content %}
        {% endblock %}
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
        <div class="container">
            <div class="text-center">
                <small>TicketList - 2018</small>
            </div>
        </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <!-- Custom scripts for this page-->
    <script src="{% static 'js/sb-admin-datatables.min.js' %}"></script>

    <!-- Simply Toast -->
    <script src="{% static 'vendor/Toast/simply-toast.js' %}"></script>

    {% block blockjs %}
    {% endblock %}

</div>
</body>

</html>